name: CI

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [dev, main]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: ./gradlew build
      - name: Detekt
        run: ./gradlew detekt