name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        type: choice
        options:
          - dev
          - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: fwilhe2/setup-kotlin@main

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Make deploy script executable
        run: chmod +x ./deploy.kts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Kotlin deploy script
        run: kotlin ./deploy.kts
        env:
          build_number: ${{ github.run_number }}
          build_vcs_number: ${{ github.sha }}
          branch: ${{ github.event.inputs.branch }}

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Copy files
        run: |
          mkdir export/
          mkdir export/connectors/
          mkdir export/modules/
          cp -r api-files/ export/
          cp connectors/*-connector/build/libs/*.jar export/connectors/
          cp services/node-service/build/libs/redicloud-node-service-*.jar export/
          cp -r start-scripts/ export/
          cp modules/*/build/libs/*.jar export/modules/
          rm export/modules/*module-handler*.jar

      - name: Publish
        run: ./gradlew publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redicloud-${{ github.event.inputs.branch }}
          path: export/
